---
- name: Start Web Server and MySQL in Docker Containers
  hosts: localhost
  become: yes

  tasks:
    - name: Start the Nginx Docker container on port 8080
      community.docker.docker_container:
        name: my_web_server_nginx
        image: nginx:latest
        ports:
          - "8081:8080"
        state: started
        
