- hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Create a Docker container with Ubuntu and run echo
      community.docker.docker_container:
        name: myubuntucontainer
        image: nginx:latest
        ports:
          - "80:80"
        state: started
