- hosts: 127.0.0.1
  become: false
  gather_facts: false

  tasks:
    - name: Create a Docker container with Ubuntu and run echo
      community.docker.docker_container:
        name: myubuntucontainer
        image: ubuntu
        command: echo "Hello"
        state: present

        
